### PR TITLE
improve lexer

### PR DESCRIPTION
**Pull request by maddanio**
this improves the lexer in a few points:
- make it independent from the compiler, just work on a string
- add row/column tracking for better error messages and debugging
- simplify and possibly fix number parsing and store numbers as string to avoid mis-parsing

### CODE REVIEW

**Comment by maddanio** [comment]
i have various parser fixes based on this one that I would submit in case this one is merged. one of them fixes a bug that I introduced myself with the streaming parser (sorry!). the upside is that after those fixes it successfully parses jakts typecheck implementation in about 1s

**Comment by maddanio** [comment]
too much? :)

**Comment by Bobbias** [comment]
Oh man, I'm sorry, I've been slacking on this project recently. I'm still working on it though, just haven't made any commits.

This is a pretty big PR to go over. I see a lot of it is just the refactor for using FileTextSpan, but there's a lot of unrelated stuff there too. I've also got a few local changes to the lexer, parser, and compiler files that haven't been committed yet.

**Comment by maddanio** [comment]
the "unrelated stuff" is actually the meat of the matter. the change in parser and elsewhere is rather mechanic. the parser change is 99% just textual replace so can easily be repeated. i mostly worked on the lexer.

**Comment by Bobbias** [comment]
I just committed a couple minor fixes I had locally, which unfortunately now means there are some merge conflicts here.

**Comment by maddanio** [comment]
no problem. if you are interested in merging this just push all you have and I will try rebasing

**Comment by Bobbias** [comment]
Alright, the repo here is now up to date with my local copy (minus a couple print statements in parsing).

Typechecking is still non-functional, but I gave up on getting it completely functional before committing.

I'm fine with merging your changes, since it is probably a better approach than how things work currently.

**Comment by maddanio** [comment]
rebased most, still have to adapt dbg_print_current

**Comment by maddanio** [comment]
rebased, but seems its stuck now, so nees further investigation

**Comment by maddanio** [comment]
now completely parsers jakts typechecker again :)

**Comment by maddanio** [comment]
ah, no, it doesnt actually, interesting, it stops without error after the first 2k characters

**Comment by Bobbias** [comment]
Interesting. I guess it's basically ready to be merged unless you would like to try to figure that out before the merge.

**Comment by maddanio** [comment]
ok, I got it to parse the first 80k of typechecker.jakt. then it gets stuck in an expression. sure, if you want to merge merge. note that I was a bit mean and ripped out your whole number parsing and simply made it store numbers as strings for now, bascially because I had problems keeping it working. but also jakt itself did that because in theory it enables you to parse very large numbers, but not sure if thats important or it was just me being lazy :)

**Comment by Bobbias** [comment]
That's fine. I mostly had that stuff because I knew eventually I'd need to use the c type numbers when it was time to start native codegen, but conversion from string to c types can be done elsewhere anyway.

**Pull request merged**
